-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgd7Tc75exVzksLRBN
j8ikP+LXefHj6XQzMJ53tOxkhuagCgYIKoZIzj0DAQehRANCAATkk/K96ed6SvHB
EGsWNnzbLXwZHl1CKz2d9i6ZSRxfyb8sxIPgjrmb/72ubhZUtz3psr5lDtHZjnUl
gYmyrqlY
-----END PRIVATE KEY-----